###
POST https://localhost:5001/api/produto/create
Content-Type: application/json

{
  "Nome": "pizza",
  "Preco": 60,
  "Descricao": "Massa de pão com fatias de queijo e recheio",
  "Quantidade": 1
}

###
PUT https://localhost:5001/api/produto/update
Content-Type: application/json

{
  "Id": 2,
  "Nome": "Espagueti",
  "Preco": 60,
  "Descricao": "Macarrão fino e comprido",
  "Quantidade": 1
}

###
GET https://localhost:5001/api/produto/list

###
GET https://localhost:5001/api/produto/getById/1

###
DELETE  https://localhost:5001/api/produto/delete/caqui
